source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/MRGBB/specs.git'
use_frameworks!

target 'GBZAuthorKit_Category_Example' do
  pod 'GBZAuthorKit_Category', :path => '../'

  target 'GBZAuthorKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
